#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-svg2pdfconverter
Version  : 1.2.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/59/3a/202cfc55f35118e9b2f3d78a5376b38a050f835e30ea9ab6f88828733a47/sphinxcontrib-svg2pdfconverter-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/59/3a/202cfc55f35118e9b2f3d78a5376b38a050f835e30ea9ab6f88828733a47/sphinxcontrib-svg2pdfconverter-1.2.0.tar.gz
Summary  : Sphinx SVG to PDF converter extension
Group    : Development/Tools
License  : BSD-3-Clause
Requires: sphinxcontrib-svg2pdfconverter-license = %{version}-%{release}
Requires: sphinxcontrib-svg2pdfconverter-python = %{version}-%{release}
Requires: sphinxcontrib-svg2pdfconverter-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
*************************************
Sphinx SVG to PDF Converter Extension
*************************************

%package license
Summary: license components for the sphinxcontrib-svg2pdfconverter package.
Group: Default

%description license
license components for the sphinxcontrib-svg2pdfconverter package.


%package python
Summary: python components for the sphinxcontrib-svg2pdfconverter package.
Group: Default
Requires: sphinxcontrib-svg2pdfconverter-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-svg2pdfconverter package.


%package python3
Summary: python3 components for the sphinxcontrib-svg2pdfconverter package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_svg2pdfconverter)
Requires: pypi(sphinx)

%description python3
python3 components for the sphinxcontrib-svg2pdfconverter package.


%prep
%setup -q -n sphinxcontrib-svg2pdfconverter-1.2.0
cd %{_builddir}/sphinxcontrib-svg2pdfconverter-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637349018
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-svg2pdfconverter
cp %{_builddir}/sphinxcontrib-svg2pdfconverter-1.2.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/sphinxcontrib-svg2pdfconverter/edb6d4112e8d9c10aa748beafecc30e8f3fc4fdf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-svg2pdfconverter/edb6d4112e8d9c10aa748beafecc30e8f3fc4fdf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
